### ISSUE TITLE
Mix-up with must_charge_vat?

### ISSUE THREAD

**Issue by wmnnd** [xavier/european_vat#1]
Hi there,

it seems like there is a mix-up with the way must_charge_vat? works (or at least the way it’s described in your Readme):
You write:
```elixir
# Buyer and seller in different EU countries, VAT number present
EuropeanVat.must_charge_vat?("NL", "BE", "BE0829071668")
# true

# Buyer and seller in different EU countries, no VAT number
EuropeanVat.must_charge_vat?("NL", "BE", nil)
# false
```
Actually the opposite is true. If buyer and seller are in different EU countries and they are both businesses (i.e. have a VAT number), no VAT has to be charged. `EuropeanVat.must_charge_vat?("NL", "BE", "BE0829071668")` should thus return `false`.
If, on the other hand, the buyer is an end-customer (i.e. with no VAT number) from another country, their local VAT rate has to be applied; `EuropeanVat.must_charge_vat?("NL", "BE", nil)` should return `true`.

To quote from the [EU website](http://europa.eu/youreurope/business/vat-customs/cross-border/index_en.htm):
> If you sell goods to another business and these goods are sent to another EU country, you do not charge VAT - if the customer has a valid VAT number.

**Comment by xavier** [comment]
Thanks a lot for the feedback!
You are right, this check is plain and simple wrong. 😇 

I never quite got to finish and actually release this library (and given that bug, I'm glad I did not) so it kind of fell off my own radar but I'll fix the issue asap and hopefully make a proper release soon.
