### ISSUE TITLE
Is this library still up-to-date?

### ISSUE THREAD

**Issue by thbar** [xavier/european_vat#2]
Thanks for sharing this code!

I wondered: are you still actively using this code in production for VAT calculations? Is the code mostly up-to-date?

Many thanks!

**Comment by xavier** [comment]
This hasn't been used in production in a while and I sort of forgot about this project which is in dire need of an update as it uses deprecated features of the language such as the `Dict` protocol.

The impeding Brexit mess might also have some impact on the behavior of this library regarding UK VAT numbers but I haven't done any research on that topic yet…

I unfortunately don't have the time to work on this library at the moment but all PRs are welcome!
